name: shell commands

on: 
  - push

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
     - name: echo string
       run: echo "hello"
     - name: Multi line string
       run: |
         pwd
         node -v
         ls -a
     - name: python command
       run: |
         import platform
         print(platform.processor())
       shell: python
jobs: 
  run-windows-commands:
    runs-on: windows-lastest
    steps:
      - name: Directory
        run: pwd
        shell: bash