name: shell commands

on: 
  - push

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

jobs: 
  terraform:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v1 
     - name: Set Terraform
       uses: hashicorp/setup-terraform@v2
       with: 
         terraform_version: 1.1.9
     - name: Terraform workflow
       run: |
          terraform init 
          terraform validate
          terraform plan
          terraform apply -auto-approve
          terraform destroy
     