name: shell commands

on: 
  - push

jobs: 
  terraform:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v1 
     - name: Set Terraform
       uses: hashicorp/setup-terraform@v2
       with: 
         terraform_version: 1.1.9
     - name: Terraform workflow
       run: |
          terraform init 
          terraform validate
          terraform apply
     